const $=s=>document.querySelector(s), view=$("#view"), toast=$("#toast");
const navItems=[["dashboard","⌂ Dashboard"],["workspace","▣ My Document"],["pdf","▤ PDF Studio"],["enhance","✦ Enhance"],["crop","⌗ Advanced Crop"],["idcard","▥ ID Card Organizer"],["image","◈ Image Tools"],["print","▦ Print Studio"],["scanner","⌁ Document Scanner"],["utilities","⚙ Utilities"],["settings","⚙ Settings"]];
const S={file:null,name:"",type:"",pages:[],page:0,rotation:0,brightness:100,contrast:100,grayscale:false,history:[],future:[]};
function msg(x){toast.innerHTML='<div class="toast">'+x+'</div>';setTimeout(()=>toast.innerHTML="",2500)}
function save(){try{localStorage.setItem("jdt-recent",JSON.stringify({name:S.name,type:S.type,thumb:S.pages[0]?.src||"",date:Date.now()}))}catch{}}
function renderNav(active="dashboard"){$("#nav").innerHTML=navItems.map(([id,t])=>'<button data-nav="'+id+'" class="'+(id===active?"active":"")+'">'+t+'</button>').join("");document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>go(b.dataset.nav))}
function go(id){renderNav(id);$("#pageTitle").textContent=navItems.find(x=>x[0]===id)?.[1].replace(/^[^ ]+ /,"")||"Dashboard";if(id==="dashboard")return dashboard();if(id==="workspace")return workspace();if(id==="pdf")return pdfStudio();if(id==="enhance")return enhance();if(id==="crop")return crop();if(id==="idcard")return idcard();if(id==="image")return imageTools();if(id==="print")return printStudio();if(id==="scanner")return scanner();if(id==="utilities")return utilities();if(id==="settings")return settings()}
function dashboard(){view.innerHTML='<div class="hero"><div class="eyebrow">SMART DIGITAL WORKSPACE</div><h2>One upload. Many possibilities.</h2><p>Upload once, then crop, enhance, arrange, convert, build PDFs and prepare print-ready documents from the same Active Document.</p><button class="btn primary" onclick="openUpload()">＋ Upload Document</button><div class="drop" id="drop">Drop JPG, PNG, WebP or PDF here<br><small>Processing stays in your browser whenever possible.</small></div></div><div class="section-title"><h2>Frequently Used</h2></div><div class="cards">'+[["▥","ID Card Organizer","Front + back cards on A4"],["✦","Enhance","Clean, sharpen and scan"],["⌗","Advanced Crop","Perspective correction"],["▦","Print Studio","Realistic A4 layouts"],["▤","PDF Studio","Merge, split and arrange"],["◈","Image Tools","Resize and compress"]].map(x=>'<div class="card" onclick="go(\''+({["ID Card Organizer":"idcard","Enhance":"enhance","Advanced Crop":"crop","Print Studio":"print","PDF Studio":"pdf","Image Tools":"image"}[x[1]])+'\')"><div style="font-size:24px">'+x[0]+'</div><h3>'+x[1]+'</h3><p>'+x[2]+'</p></div>').join("")+'</div>';bindDrop()}
function openUpload(){$("#fileInput").click()}
async function loadFile(f){if(!f)return;if(!/\.(jpe?g|png|webp|pdf)$/i.test(f.name)){msg("Unsupported file type");return}S.file=f;S.name=f.name;S.type=f.type;S.pages=[];S.page=0;S.rotation=0;S.history=[];S.future=[];if(f.type==="application/pdf"||/\.pdf$/i.test(f.name)){await loadPDF(f)}else{const src=await readData(f);S.pages=[{src,name:f.name,rotation:0}]}save();msg("Document loaded");go("workspace")}
function readData(f){return new Promise((res,rej)=>{const r=new FileReader;r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
async function loadPDF(f){try{const pdf=await pdfjs(f);S.pages=pdf.map((src,i)=>({src,name:"Page "+(i+1),rotation:0}))}catch(e){msg("PDF preview needs a modern browser; export tools remain available.")}}
async function pdfjs(f){if(!window.pdfjsLib){await new Promise((res,rej)=>{const s=document.createElement("script");s.src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs";s.type="module";s.onload=res;s.onerror=rej;document.head.appendChild(s)})}return []}
function workspace(){if(!S.pages.length){view.innerHTML='<div class="empty"><h2>No active document</h2><p>Upload a document to start the shared workspace.</p><button class="btn primary" onclick="openUpload()">Upload Document</button></div>';return}view.innerHTML='<div class="workspace"><div class="canvas-panel"><div class="preview"><img id="mainImg" src="'+S.pages[S.page].src+'"></div><div class="toolbar"><button class="tool" onclick="rotate(90)">↻ Rotate</button><button class="tool" onclick="rotate(-90)">↺ Rotate</button><button class="tool" onclick="flip()">↔ Flip</button><button class="tool" onclick="undo()">Undo</button><button class="tool" onclick="redo()">Redo</button><button class="tool" onclick="resetPage()">Reset</button></div><div class="page-grid">'+S.pages.map((p,i)=>'<div class="thumb" onclick="S.page='+i+';workspace()"><img src="'+p.src+'"><small>Page '+(i+1)+'</small></div>').join("")+'</div></div><div class="tools-panel"><h3>Active Document</h3><p>'+esc(S.name)+'</p><p class="muted">'+S.pages.length+' page(s)</p><button class="btn primary" style="width:100%" onclick="downloadCurrent()">Export JPG</button><button class="btn" style="width:100%;margin-top:8px" onclick="imageToPDF()">Export PDF</button><hr><button class="tool" onclick="go('crop')">Advanced Crop →</button><button class="tool" onclick="go('enhance')">Enhance →</button><button class="tool" onclick="go('print')">Print Studio →</button></div></div>'}
function snapshot(){S.history.push(JSON.stringify(S.pages));if(S.history.length>20)S.history.shift();S.future=[]}
function rotate(a){snapshot();S.pages[S.page].rotation=(S.pages[S.page].rotation+a+360)%360;workspace()}
function flip(){snapshot();S.pages[S.page].flip=!S.pages[S.page].flip;workspace()}
function resetPage(){snapshot();S.pages[S.page].rotation=0;S.pages[S.page].flip=false;workspace()}
function undo(){if(!S.history.length)return;S.future.push(JSON.stringify(S.pages));S.pages=JSON.parse(S.history.pop());workspace()}
function redo(){if(!S.future.length)return;S.history.push(JSON.stringify(S.pages));S.pages=JSON.parse(S.future.pop());workspace()}
function enhance(){if(!S.pages.length)return noDoc();view.innerHTML='<div class="workspace"><div class="canvas-panel"><div class="preview"><img id="enhImg" src="'+S.pages[S.page].src+'" style="filter:brightness('+S.brightness+'%) contrast('+S.contrast+'%)'+(S.grayscale?' grayscale(1)':'')+'"></div></div><div class="tools-panel"><h3>Enhancer</h3><label>Brightness <output id="bv">'+S.brightness+'</output></label><input type="range" min="40" max="160" value="'+S.brightness+'" oninput="S.brightness=+this.value;$('#+'bv').textContent=this.value;$('#+'enhImg').style.filter=filters()"><label>Contrast <output id="cv">'+S.contrast+'</output></label><input type="range" min="40" max="180" value="'+S.contrast+'" oninput="S.contrast=+this.value;$('#+'cv').textContent=this.value;$('#+'enhImg').style.filter=filters()"><label>Scan mode</label><select id="mode" onchange="modeEnh(this.value)"><option>Clean Document</option><option>Print Ready</option><option>Text Scan</option><option>B&W Scan</option><option>ID Card</option><option>Photo Document</option></select><button class="btn primary" style="width:100%;margin-top:16px" onclick="applyEnhance()">Apply Enhancement</button></div></div>'}
function filters(){return 'brightness('+S.brightness+'%) contrast('+S.contrast+'%)'+(S.grayscale?' grayscale(1)':'')}
function modeEnh(v){S.grayscale=v==="B&W Scan"||v==="Text Scan";if(v==="Print Ready"){S.brightness=108;S.contrast=125}if(v==="ID Card"){S.brightness=105;S.contrast=115}enhance()}
async function applyEnhance(){if(!S.pages.length)return;const img=await imageBitmap(S.pages[S.page].src),c=document.createElement("canvas");c.width=img.width;c.height=img.height;const x=c.getContext("2d");x.filter=filters();x.drawImage(img,0,0);S.pages[S.page].src=c.toDataURL("image/jpeg",.94);save();msg("Enhancement applied");workspace()}
function imageBitmap(src){return new Promise((res,rej)=>{const i=new Image;i.onload=()=>res(i);i.onerror=rej;i.src=src})}
function crop(){if(!S.pages.length)return noDoc();view.innerHTML='<div class="workspace"><div class="canvas-panel"><div class="preview"><img id="cropImg" src="'+S.pages[S.page].src+'"></div></div><div class="tools-panel"><h3>Advanced Crop</h3><p class="muted">Browser crop with presets. Perspective correction can be done interactively with the four-corner overlay in the next canvas revision.</p><select id="cropPreset"><option value="free">Free</option><option value="a4">A4</option><option value="a5">A5</option><option value="id">ID Card</option><option value="passport">Passport</option></select><label>Rotation</label><input type="range" min="-45" max="45" value="0" id="angle"><button class="btn primary" style="width:100%;margin-top:16px" onclick="cropPreset()">Apply Crop Preset</button></div></div>'}
async function cropPreset(){const p=$("#cropPreset").value;if(p==="free"){msg("Free crop is available by browser image editing; choose a preset for exact ratio.");return}const img=await imageBitmap(S.pages[S.page].src);let ratio=p==="a4"?210/297:p==="a5"?148/210:p==="id"?85.6/53.98:35/45;let w=img.width,h=img.height,tw=w,th=w/ratio;if(th>h){th=h;tw=h*ratio}const c=document.createElement("canvas");c.width=Math.round(tw);c.height=Math.round(th);c.getContext("2d").drawImage(img,(w-tw)/2,(h-th)/2,tw,th,0,0,tw,th);snapshot();S.pages[S.page].src=c.toDataURL("image/jpeg",.95);workspace();msg("Crop applied")}
function idcard(){view.innerHTML='<div class="hero"><div class="eyebrow">PRINT-READY ID CARD WORKSPACE</div><h2>Front + Back → A4</h2><p>Build a card layout from the active document. Default physical size is 85.60 × 53.98 mm.</p><button class="btn primary" onclick="go(\'print\')">Open Print Studio</button></div><div class="cards"><div class="card"><h3>Default size</h3><p>85.60 × 53.98 mm</p></div><div class="card"><h3>Layout</h3><p>Front + back, adjustable gap, margin and scale.</p></div><div class="card"><h3>Export</h3><p>JPG, PNG or A4 PDF.</p></div></div>'}
function imageTools(){if(!S.pages.length)return noDoc();view.innerHTML='<div class="cards"><div class="card"><h3>Convert</h3><p>Export current page as JPG or PNG.</p><button class="btn" onclick="downloadCurrent(\'png\')">PNG</button> <button class="btn" onclick="downloadCurrent(\'jpg\')">JPG</button></div><div class="card"><h3>Resize</h3><label>Width (px)</label><input id="rw" type="text" value="1200"><button class="btn primary" style="margin-top:10px" onclick="resizeImage()">Resize & Export</button></div><div class="card"><h3>Compression</h3><label>Quality</label><input id="quality" type="range" min="20" max="100" value="85"><button class="btn primary" onclick="compressImage()">Compress & Export</button></div></div>'}
async function resizeImage(){const img=await imageBitmap(S.pages[S.page].src),w=Math.max(1,+$("#rw").value||img.width),h=Math.round(img.height*w/img.width),c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);downloadData(c.toDataURL("image/jpeg",.92),"resized.jpg")}
async function compressImage(){const img=await imageBitmap(S.pages[S.page].src),c=document.createElement("canvas");c.width=img.width;c.height=img.height;c.getContext("2d").drawImage(img,0,0);downloadData(c.toDataURL("image/jpeg",+$("#quality").value/100),"compressed.jpg")}
function printStudio(){if(!S.pages.length)return noDoc();view.innerHTML='<div class="workspace"><div class="canvas-panel"><h3>A4 Print Preview</h3><div id="a4" style="background:white;color:#111;min-height:650px;max-width:460px;margin:auto;padding:28px;display:grid;grid-template-columns:1fr 1fr;gap:12px;align-content:start">'+S.pages.map(p=>'<div style="border:1px solid #bbb;aspect-ratio:85.6/53.98;overflow:hidden"><img src="'+p.src+'" style="width:100%;height:100%;object-fit:contain;transform:rotate('+p.rotation+'deg)"></div>').join("")+'</div></div><div class="tools-panel"><h3>Print Layout Studio</h3><label>Items per page</label><select id="ipp" onchange="msg(this.value+\' items selected\')"><option>1</option><option>2</option><option selected>4</option><option>6</option><option>8</option></select><label>Paper</label><select><option>A4</option><option>A5</option><option>A3</option><option>Letter</option><option>Legal</option><option>Custom</option></select><label>Margin (mm)</label><input type="range" min="0" max="30" value="10"><label>Gap (mm)</label><input type="range" min="0" max="20" value="4"><button class="btn primary" style="width:100%;margin-top:16px" onclick="imageToPDF()">Export A4 PDF</button><button class="btn" style="width:100%;margin-top:8px" onclick="window.print()">Print</button></div></div>'}
function pdfStudio(){view.innerHTML='<div class="hero"><div class="eyebrow">PDF STUDIO</div><h2>Arrange, merge and export</h2><p>Use the active document pages for quick PDF creation. Add more images from the upload button.</p><button class="btn primary" onclick="imageToPDF()">Export current pages to PDF</button></div><div class="section-title"><h2>Pages</h2><button class="btn" onclick="openUpload()">＋ Add files</button></div><div class="page-grid">'+(S.pages.length?S.pages.map((p,i)=>'<div class="thumb"><img src="'+p.src+'"><small>Page '+(i+1)+' <button class="tool" onclick="deletePage('+i+')">Delete</button></small></div>').join(""):'<div class="empty">No pages loaded.</div>')+'</div>'}
function deletePage(i){S.pages.splice(i,1);S.page=Math.max(0,Math.min(S.page,S.pages.length-1));pdfStudio()}
async function imageToPDF(){if(!S.pages.length)return noDoc();const {jsPDF}=window.jspdf;const pdf=new jsPDF("p","mm","a4");for(let i=0;i<S.pages.length;i++){if(i)pdf.addPage();const img=await imageBitmap(S.pages[i].src),ratio=img.width/img.height;let w=190,h=w/ratio;if(h>277){h=277;w=h*ratio}pdf.addImage(S.pages[i].src,"JPEG",(210-w)/2,(297-h)/2,w,h)}pdf.save((S.name||"document").replace(/\.[^.]+$/,"")+".pdf");msg("PDF exported")}
function downloadCurrent(ext="jpg"){if(!S.pages.length)return noDoc();const p=S.pages[S.page];if(ext==="png")return downloadData(p.src,"page.png");if(ext==="jpg")return downloadData(p.src,"page.jpg");downloadData(p.src,"page.jpg")}
function downloadData(data,name){const a=document.createElement("a");a.href=data;a.download=name;a.click()}
function scanner(){view.innerHTML='<div class="hero"><div class="eyebrow">DOCUMENT SCANNER</div><h2>Camera capture</h2><p>Use your phone camera to capture a document, then continue through Crop → Enhance → PDF.</p><button class="btn primary" onclick="openUpload()">Open Camera / Gallery</button><input type="file" accept="image/*" capture="environment" onchange="loadFile(this.files[0])" style="margin-top:16px"></div>'}
function utilities(){view.innerHTML='<div class="cards">'+[["Blank A4","Generate a clean A4 PDF"],["Image Dimensions","Inspect current image"],["File Size","Check selected file size"],["PDF Page Counter","Count active pages"],["Metadata","Show file metadata"],["Page Extraction","Export selected page"],["Rename","Change export filename"],["Signature Resize","Resize signature using image tools"]].map((x,i)=>'<div class="card"><h3>'+x[0]+'</h3><p>'+x[1]+'</p><button class="btn" onclick="utility('+i+')">Open</button></div>').join("")+'</div>'}
function utility(i){if(i===1&&S.pages.length){imageBitmap(S.pages[S.page].src).then(x=>msg(x.width+" × "+x.height+" px"))}else if(i===2&&S.file)msg((S.file.size/1024).toFixed(1)+" KB");else if(i===3)msg(S.pages.length+" page(s)");else msg("Utility opened.")}
function settings(){view.innerHTML='<div class="cards"><div class="card"><h3>Privacy</h3><p>Processing is client-side where possible. Files are not intentionally uploaded by this app.</p></div><div class="card"><h3>Recent documents</h3><p>Stored locally in browser storage.</p><button class="btn danger" onclick="localStorage.removeItem(\'jdt-recent\');msg(\'Recent data cleared\')">Clear recent</button></div><div class="card"><h3>About</h3><p>Jangira E Mitra — Smart Document Toolkit<br>One Upload. Many Possibilities.</p></div></div>'}
function noDoc(){msg("Upload a document first");go("dashboard")}function esc(s){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function bindDrop(){const d=$("#drop");if(!d)return;d.ondragover=e=>{e.preventDefault();d.classList.add("drag")};d.ondragleave=()=>d.classList.remove("drag");d.ondrop=e=>{e.preventDefault();d.classList.remove("drag");loadFile(e.dataTransfer.files[0])}}
$("#uploadBtn").onclick=openUpload;$("#fileInput").onchange=e=>loadFile(e.target.files[0]);$("#openRecent").onclick=()=>{const r=JSON.parse(localStorage.getItem("jdt-recent")||"null");if(r?.thumb){S.name=r.name;S.pages=[{src:r.thumb,name:r.name}];go("workspace")}else msg("No recent document")};$("#menu").onclick=()=>$(".sidebar").classList.toggle("open");renderNav();dashboard();