(()=>{
  const $=s=>document.querySelector(s);
  function readData(f){return new Promise((r,j)=>{const x=new FileReader;x.onload=()=>r(x.result);x.onerror=j;x.readAsDataURL(f)})}
  async function pagesFrom(f){if(f.type==='application/pdf'||/\.pdf$/i.test(f.name)){if(!window.pdfjsLib)throw Error('PDF engine unavailable');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const pdf=await pdfjsLib.getDocument({data:await f.arrayBuffer()}).promise,a=[];for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n),v=p.getViewport({scale:1.5}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;a.push({src:c.toDataURL('image/jpeg',.94),name:'Page '+n,rotation:0,flip:false})}return a}return[{src:await readData(f),name:f.name,rotation:0,flip:false}]}
  window.loadFiles=async files=>{files=[...files].filter(f=>/\.(jpe?g|png|webp|pdf)$/i.test(f.name));if(!files.length)return msg('Choose JPG, PNG, WebP or PDF');try{if(!S.pages.length){S.file=files[0];S.name=files[0].name;S.type=files[0].type;S.pages=[];S.page=0;S.history=[];S.future=[]}for(const f of files){const ps=await pagesFrom(f);S.pages.push(...ps.map((p,i)=>({...p,name:files.length>1?f.name+' • '+(i+1):p.name,source:f.name})))}saveRecent();msg(files.length+' file(s) added');go('workspace')}catch(e){console.error(e);msg('Could not load selected file(s)')}};
  window.loadFile=f=>f&&loadFiles([f]);
  window.pdfStudio=()=>{if(!S.pages.length)return noDoc();view.innerHTML='<div class="hero"><div class="eyebrow">PDF STUDIO</div><h2>Page Organizer</h2><p>Reorder, rotate, duplicate, delete and extract pages from the active document.</p><button class="btn primary" onclick="imageToPDF()">Export PDF</button> <button class="btn" onclick="openUpload()">＋ Add files</button></div><div class="page-grid">'+S.pages.map((p,i)=>'<div class="thumb"><img src="'+p.src+'"><small><b>Page '+(i+1)+'</b><br><button class="tool" onclick="movePdfPage('+i+',-1)">←</button> <button class="tool" onclick="movePdfPage('+i+',1)">→</button> <button class="tool" onclick="dupPdfPage('+i+')">Duplicate</button> <button class="tool" onclick="rotPdfPage('+i+')">↻</button> <button class="tool" onclick="extractPdfPage('+i+')">Extract</button> <button class="tool" onclick="delPdfPage('+i+')">Delete</button></small></div>').join('')+'</div>'};
  window.movePdfPage=(i,d)=>{if(i+d<0||i+d>=S.pages.length)return;snapshot();[S.pages[i],S.pages[i+d]]=[S.pages[i+d],S.pages[i]];S.page=i+d;pdfStudio()};
  window.dupPdfPage=i=>{snapshot();S.pages.splice(i+1,0,{...S.pages[i],name:S.pages[i].name+' copy'});pdfStudio()};
  window.rotPdfPage=i=>{snapshot();S.pages[i].rotation=(S.pages[i].rotation+90)%360;pdfStudio()};
  window.delPdfPage=i=>{snapshot();S.pages.splice(i,1);S.page=Math.max(0,Math.min(S.page,S.pages.length-1));S.pages.length?pdfStudio():go('dashboard')};
  window.extractPdfPage=async i=>{const {jsPDF}=window.jspdf,p=new jsPDF('p','mm','a4'),img=S.pages[i];p.addImage(img.src,'JPEG',10,10,190,277,undefined,'FAST');p.save('page-'+(i+1)+'.pdf');msg('Page extracted')};
  window.exportPagesToPDF=async(pages,name='document.pdf',paper='A4',margin=10,gap=4,ipp=1)=>{const {jsPDF}=window.jspdf;if(!jsPDF)return msg('PDF engine unavailable');const sz={A4:[210,297],A5:[148,210],A3:[297,420],Letter:[215.9,279.4],Legal:[215.9,355.6]}[paper]||[210,297];const pdf=new jsPDF('p','mm',sz);let k=0,pageNo=0;while(k<pages.length){if(pageNo++)pdf.addPage(sz,'p');const cols=Math.ceil(Math.sqrt(ipp)),rows=Math.ceil(ipp/cols),cw=(sz[0]-2*margin-(cols-1)*gap)/cols,ch=(sz[1]-2*margin-(rows-1)*gap)/rows;for(let n=0;n<ipp&&k<pages.length;n++,k++){const im=new Image;im.src=pages[k].src;await new Promise(r=>im.onload=r);let w=cw,h=w*im.height/im.width;if(h>ch){h=ch;w=h*im.width/im.height}const col=n%cols,row=Math.floor(n/cols);pdf.addImage(pages[k].src,'JPEG',margin+col*(cw+gap)+(cw-w)/2,margin+row*(ch+gap)+(ch-h)/2,w,h,undefined,'FAST')}}pdf.save(name);msg('PDF exported')};
  window.printStudio=()=>{if(!S.pages.length)return noDoc();const p=S.print||{paper:'A4',ipp:4,margin:10,gap:4,fit:'contain',rotation:0};view.innerHTML='<div class="workspace"><div class="canvas-panel"><h3>'+p.paper+' Print Preview</h3><div style="background:#fff;color:#111;min-height:650px;max-width:500px;margin:auto;padding:28px;display:grid;grid-template-columns:repeat('+Math.ceil(Math.sqrt(p.ipp))+',1fr);gap:12px">'+S.pages.map(q=>'<div style="border:1px solid #aaa;min-height:80px;display:flex;align-items:center;justify-content:center;overflow:hidden"><img src="'+q.src+'" style="max-width:100%;max-height:100%;object-fit:'+p.fit+';transform:rotate('+p.rotation+'deg)"></div>').join('')+'</div></div><div class="tools-panel"><h3>Print Layout Studio</h3><label>Paper</label><select id="psPaper"><option>A4</option><option>A5</option><option>A3</option><option>Letter</option><option>Legal</option></select><label>Items per page</label><select id="psIpp">'+[1,2,4,6,8].map(n=>'<option value="'+n+'" '+(p.ipp===n?'selected':'')+'>'+n+'</option>').join('')+'</select><label>Margin (mm): <output id="psM">'+p.margin+'</output></label><input id="psMargin" type="range" min="0" max="30" value="'+p.margin+'"><label>Gap (mm): <output id="psG">'+p.gap+'</output></label><input id="psGap" type="range" min="0" max="20" value="'+p.gap+'"><label>Fit</label><select id="psFit"><option value="contain">Fit</option><option value="cover">Fill</option></select><label>Rotation</label><input id="psRot" type="range" min="-180" max="180" value="'+p.rotation+'"><button class="btn primary" style="width:100%;margin-top:16px" onclick="applyPrintSettings()">Update Preview</button><button class="btn primary" style="width:100%;margin-top:8px" onclick="exportPagesToPDF(S.pages,\'print-layout.pdf\',S.print.paper,S.print.margin,S.print.gap,S.print.ipp)">Export Print PDF</button><button class="btn" style="width:100%;margin-top:8px" onclick="window.print()">Print</button></div></div>';psPaper.value=p.paper;psFit.value=p.fit;psM.oninput=null;psMargin.oninput=()=>psM.textContent=psMargin.value;psGap.oninput=()=>psG.textContent=psGap.value};
  window.applyPrintSettings=()=>{S.print={paper:psPaper.value,ipp:+psIpp.value,margin:+psMargin.value,gap:+psGap.value,fit:psFit.value,rotation:+psRot.value};printStudio()};
  window.idcard=()=>{if(!S.pages.length)return noDoc();const d=S.id||{w:85.6,h:53.98,gap:6,margin:10};view.innerHTML='<div class="workspace"><div class="canvas-panel"><h3>ID Card A4 Layout</h3><div style="background:#fff;color:#111;max-width:500px;margin:auto;padding:24px;display:grid;grid-template-columns:1fr 1fr;gap:'+d.gap+'px">'+S.pages.slice(0,8).map(p=>'<div style="border:1px solid #aaa;aspect-ratio:'+d.w+'/'+d.h+';overflow:hidden"><img src="'+p.src+'" style="width:100%;height:100%;object-fit:fill"></div>').join('')+'</div></div><div class="tools-panel"><h3>Physical Card Size</h3><label>Width (mm)</label><input id="idW" type="number" step="0.01" value="'+d.w+'"><label>Height (mm)</label><input id="idH" type="number" step="0.01" value="'+d.h+'"><label>Gap (mm)</label><input id="idG" type="number" step="0.5" value="'+d.gap+'"><label>Margin (mm)</label><input id="idM" type="number" step="0.5" value="'+d.margin+'"><button class="btn primary" style="width:100%;margin-top:16px" onclick="exportIDCards()">Export A4 PDF</button><p class="muted">Pages are treated as card images. Use page 1 for front and page 2 for back when preparing a pair.</p></div></div>';};
  window.exportIDCards=async()=>{S.id={w:+idW.value||85.6,h:+idH.value||53.98,gap:+idG.value||6,margin:+idM.value||10};const {jsPDF}=window.jspdf,pdf=new jsPDF('p','mm','a4'),cols=Math.max(1,Math.floor((210-2*S.id.margin+S.id.gap)/(S.id.w+S.id.gap))),rows=Math.max(1,Math.floor((297-2*S.id.margin+S.id.gap)/(S.id.h+S.id.gap)));for(let i=0;i<Math.min(S.pages.length,cols*rows);i++){const c=i%cols,r=Math.floor(i/cols);pdf.addImage(S.pages[i].src,'JPEG',S.id.margin+c*(S.id.w+S.id.gap),S.id.margin+r*(S.id.h+S.id.gap),S.id.w,S.id.h,undefined,'FAST')}pdf.save('id-card-a4.pdf');msg('A4 ID card PDF exported')};
})();
  window.go=id=>{renderNav(id);const t=navItems.find(x=>x[0]===id);if($('\\#pageTitle'))$('\\#pageTitle').textContent=t?t[1].replace(/^[^ ]+ /,''):'Dashboard';const fn={dashboard:window.dashboard,workspace:window.workspace,pdf:window.pdfStudio,enhance:window.enhance,crop:window.crop,idcard:window.idcard,image:window.imageTools,print:window.printStudio,scanner:window.scanner,utilities:window.utilities,settings:window.settings}[id];if(fn)fn()};
  window.renderNav=active=>{$('#nav').innerHTML=navItems.map(x=>'<button data-nav="'+x[0]+'" class="'+(x[0]===active?'active':'')+'">'+x[1]+'</button>').join('');document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>window.go(b.dataset.nav))};
  $('#uploadBtn').onclick=openUpload;$('#fileInput').onchange=e=>{window.loadFiles(e.target.files);e.target.value=''};window.renderNav('dashboard');
})();